export interface ExternalFormulaEntry {
  chapterId: string;
  name: string;
  latex: string;
  sourceName: string;
  sourceUrl?: string;
  sourceDetail?: string;
  sourcePageHint?: string;
  usageNote?: string;
  pitfallNote?: string;
  variableGuide?: string[];
}

export interface FormulaSourceDoc {
  subject: 'Physics' | 'Chemistry' | 'Biology' | 'Math' | 'Commerce';
  sourceName: string;
  localPath: string;
  sourceUrl?: string;
}

export const FORMULA_SOURCE_DOCS: FormulaSourceDoc[] = [
  { subject: 'Math', sourceName: 'Maths book 3.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Maths book 3.pdf' },
  {
    subject: 'Math',
    sourceName: 'documents_148581-489262829-class-12-mathematics-all-formulas.pdf',
    localPath: 'C:\\Users\\adith\\Downloads\\documents_148581-489262829-class-12-mathematics-all-formulas.pdf',
  },
  { subject: 'Math', sourceName: 'Maths formulas.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Maths formulas.pdf' },
  { subject: 'Biology', sourceName: 'Formula-Book_Biology-1.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Formula-Book_Biology-1.pdf' },
  { subject: 'Chemistry', sourceName: 'Chemistry formula 3.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Chemistry formula 3.pdf' },
  { subject: 'Chemistry', sourceName: 'Chemistry formulas part 2.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Chemistry formulas part 2.pdf' },
  { subject: 'Chemistry', sourceName: 'Chemistry formulas.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Chemistry formulas.pdf' },
  { subject: 'Physics', sourceName: 'Physics formula part 2.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Physics formula part 2.pdf' },
  { subject: 'Physics', sourceName: 'Physics formula booklet.pdf', localPath: 'C:\\Users\\adith\\Downloads\\Physics formula booklet.pdf' },
  {
    subject: 'Commerce',
    sourceName: 'Class 12 Accountancy Ratio Chapter (reference)',
    localPath: 'Web reference',
    sourceUrl: 'https://www.vedantu.com/content-files-downloadable/ncert-solutions/ncert-solutions-class-12-accountancy-company-accounts-and-analysis-of-financial-statements-chapter-5.pdf',
  },
  {
    subject: 'Commerce',
    sourceName: 'Break-even formula reference',
    localPath: 'Web reference',
    sourceUrl: 'https://www.investopedia.com/ask/answers/032715/how-can-i-calculate-breakeven-analysis-excel.asp',
  },
];

export const EXTERNAL_FORMULA_ENTRIES: ExternalFormulaEntry[] = [
  { chapterId: 'c10-chem-2', name: 'pH', latex: '\\mathrm{pH} = -\\log[H^+]', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-chem-2', name: 'pOH', latex: '\\mathrm{pOH} = -\\log[OH^-]', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-chem-2', name: 'Ionic Product of Water', latex: 'K_w = [H^+][OH^-] = 10^{-14}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-chem-4', name: 'Ethanol Combustion', latex: 'C_2H_5OH + 3O_2 \\rightarrow 2CO_2 + 3H_2O', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-chem-4', name: 'Esterification', latex: 'CH_3COOH + C_2H_5OH \\rightleftharpoons CH_3COOC_2H_5 + H_2O', sourceName: 'NCERT formula set (curated)' },

  { chapterId: 'c10-phy-1', name: 'Mirror Formula', latex: '\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-1', name: 'Mirror Magnification', latex: 'm = \\frac{h_i}{h_o} = -\\frac{v}{u}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-1', name: 'Lens Formula', latex: '\\frac{1}{f} = \\frac{1}{v} - \\frac{1}{u}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-1', name: 'Lens Magnification', latex: 'm = \\frac{h_i}{h_o} = \\frac{v}{u}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-1', name: 'Power of Lens', latex: 'P = \\frac{1}{f(\\mathrm{m})}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: "Ohm's Law", latex: 'V = IR', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: 'Resistivity Relation', latex: 'R = \\rho\\frac{l}{A}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: 'Series Resistance', latex: 'R = R_1 + R_2 + R_3 + \\cdots', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: 'Parallel Resistance', latex: '\\frac{1}{R} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\frac{1}{R_3} + \\cdots', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: 'Electrical Power', latex: 'P = VI = I^2R = \\frac{V^2}{R}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-3', name: "Joule's Law of Heating", latex: 'H = I^2Rt', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-4', name: 'Magnetic Field around Straight Conductor', latex: 'B = \\frac{\\mu_0 I}{2\\pi r}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-phy-4', name: 'Magnetic Field in a Solenoid', latex: 'B = \\mu_0 n I', sourceName: 'NCERT formula set (curated)' },

  { chapterId: 'c10-math-3', name: 'Cross-Multiplication Formula for x', latex: 'x = \\frac{b_1c_2 - b_2c_1}{a_1b_2 - a_2b_1}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-3', name: 'Cross-Multiplication Formula for y', latex: 'y = \\frac{c_1a_2 - c_2a_1}{a_1b_2 - a_2b_1}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-4', name: 'Quadratic Formula', latex: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-4', name: 'Discriminant', latex: 'D = b^2 - 4ac', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-5', name: 'nth Term of AP', latex: 'a_n = a + (n-1)d', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-5', name: 'Sum of n Terms of AP', latex: 'S_n = \\frac{n}{2}[2a + (n-1)d] = \\frac{n}{2}(a + l)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-7', name: 'Distance Formula', latex: '\\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-7', name: 'Section Formula', latex: '\\left(\\frac{mx_2 + nx_1}{m+n}, \\frac{my_2 + ny_1}{m+n}\\right)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-7', name: 'Midpoint Formula', latex: '\\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-7', name: 'Area of Triangle in Coordinates', latex: '\\frac{1}{2}\\left|x_1(y_2-y_3) + x_2(y_3-y_1) + x_3(y_1-y_2)\\right|', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-8', name: 'tan theta Relation', latex: '\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-8', name: 'Trig Identity', latex: '\\sin^2\\theta + \\cos^2\\theta = 1', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-8', name: 'Sec-Tan Identity', latex: '1 + \\tan^2\\theta = \\sec^2\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-8', name: 'Cosec-Cot Identity', latex: '1 + \\cot^2\\theta = \\cosec^2\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-11', name: 'Circumference of Circle', latex: '2\\pi r', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-11', name: 'Area of Circle', latex: '\\pi r^2', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-11', name: 'Area of Sector', latex: '\\frac{\\theta}{360^\\circ}\\pi r^2', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-11', name: 'Length of Arc', latex: '\\frac{\\theta}{360^\\circ}2\\pi r', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-12', name: 'Volume of Cylinder', latex: '\\pi r^2 h', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-12', name: 'Total Surface Area of Cylinder', latex: '2\\pi r(h+r)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-12', name: 'Volume of Cone', latex: '\\frac{1}{3}\\pi r^2 h', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-12', name: 'Surface Area of Sphere', latex: '4\\pi r^2', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-12', name: 'Volume of Sphere', latex: '\\frac{4}{3}\\pi r^3', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c10-math-14', name: 'Classical Probability', latex: 'P(E) = \\frac{\\text{Number of favourable outcomes}}{\\text{Total number of outcomes}}', sourceName: 'NCERT formula set (curated)' },

  { chapterId: 'c12-phy-1', name: "Coulomb's Law", latex: 'F = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1 q_2}{r^2}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-1', name: 'Electric Field due to Point Charge', latex: 'E = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q}{r^2}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-1', name: 'Electric Flux', latex: '\\Phi_E = \\vec{E}\\cdot\\vec{A} = EA\\cos\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-1', name: "Gauss's Law", latex: '\\oint \\vec{E}\\cdot d\\vec{A} = \\frac{q_{\\mathrm{enc}}}{\\varepsilon_0}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-2', name: 'Electric Potential', latex: 'V = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q}{r}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-2', name: 'Capacitance', latex: 'C = \\frac{Q}{V}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-2', name: 'Parallel Plate Capacitance', latex: 'C = \\frac{\\varepsilon_0 A}{d}', sourceName: 'Physics formula part 2.pdf' },
  { chapterId: 'c12-phy-2', name: 'Energy Stored in Capacitor', latex: 'U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C} = \\frac{1}{2}QV', sourceName: 'Physics formula part 2.pdf' },
  { chapterId: 'c12-phy-3', name: "Ohm's Law", latex: 'V = IR', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-3', name: 'Electrical Power', latex: 'P = VI = I^2R = \\frac{V^2}{R}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-3', name: 'Resistivity Relation', latex: 'R = \\rho\\frac{l}{A}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-4', name: 'Magnetic Force on a Charge', latex: 'F = qvB\\sin\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-4', name: 'Magnetic Force on a Conductor', latex: 'F = BIl\\sin\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-4', name: 'Magnetic Field around Long Straight Wire', latex: 'B = \\frac{\\mu_0 I}{2\\pi r}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-6', name: "Faraday's Law", latex: '\\mathcal{E} = -\\frac{d\\Phi_B}{dt}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-6', name: 'Self-inductance', latex: 'L = \\frac{N\\Phi}{I}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-6', name: 'Energy in Inductor', latex: 'U = \\frac{1}{2}LI^2', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-7', name: 'AC RMS Current', latex: 'I_{\\mathrm{rms}} = \\frac{I_0}{\\sqrt{2}}', sourceName: 'Physics formula part 2.pdf' },
  { chapterId: 'c12-phy-7', name: 'AC RMS Voltage', latex: 'V_{\\mathrm{rms}} = \\frac{V_0}{\\sqrt{2}}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-7', name: 'Inductive Reactance', latex: 'X_L = \\omega L', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-7', name: 'Capacitive Reactance', latex: 'X_C = \\frac{1}{\\omega C}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-7', name: 'Impedance of LCR Circuit', latex: 'Z = \\sqrt{R^2 + (X_L - X_C)^2}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-7', name: 'Average AC Power', latex: 'P = V_{\\mathrm{rms}}I_{\\mathrm{rms}}\\cos\\phi', sourceName: 'Physics formula part 2.pdf' },
  { chapterId: 'c12-phy-7', name: 'Transformer Ratio', latex: '\\frac{V_s}{V_p} = \\frac{N_s}{N_p}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-8', name: 'Speed of Electromagnetic Waves', latex: 'c = \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-8', name: 'Field Amplitude Relation', latex: 'E_0 = cB_0', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-8', name: 'Wave Speed Relation', latex: '\\nu\\lambda = c', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-9', name: 'Mirror Formula', latex: '\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-9', name: 'Lens Formula', latex: '\\frac{1}{f} = \\frac{1}{v} - \\frac{1}{u}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-9', name: 'Lens Maker Formula', latex: '\\frac{1}{f} = (\\mu-1)\\left(\\frac{1}{R_1}-\\frac{1}{R_2}\\right)', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-10', name: 'Fringe Width in YDSE', latex: '\\beta = \\frac{\\lambda D}{d}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-10', name: "Brewster's Law", latex: '\\mu = \\tan i_p', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-10', name: "Malus' Law", latex: 'I = I_0\\cos^2\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-11', name: "de Broglie Wavelength", latex: '\\lambda = \\frac{h}{p} = \\frac{h}{mv}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-11', name: "Einstein's Photoelectric Equation", latex: 'h\\nu = \\phi + K_{\\max}', sourceName: 'Physics formula booklet.pdf' },
  { chapterId: 'c12-phy-12', name: 'Bohr Radius', latex: 'r_n = \\frac{n^2 a_0}{Z}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-12', name: 'Bohr Energy', latex: 'E_n = -\\frac{13.6 Z^2}{n^2}\\ \\mathrm{eV}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-12', name: 'Rydberg Formula', latex: '\\frac{1}{\\lambda} = RZ^2\\left(\\frac{1}{n_1^2} - \\frac{1}{n_2^2}\\right)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-13', name: 'Radioactive Decay Law', latex: 'N = N_0 e^{-\\lambda t}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-13', name: 'Half-life', latex: 'T_{1/2} = \\frac{0.693}{\\lambda}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-13', name: 'Mass-Energy Equivalence', latex: 'E = \\Delta mc^2', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-phy-14', name: 'Transistor Current Gain', latex: '\\beta = \\frac{I_C}{I_B}', sourceName: 'NCERT formula set (curated)' },

  { chapterId: 'c12-chem-2', name: "Raoult's Law", latex: 'p_i = x_i p_i^\\circ', sourceName: 'Chemistry formulas.pdf' },
  { chapterId: 'c12-chem-2', name: 'Molarity', latex: 'M = \\frac{n}{V(\\mathrm{L})}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-2', name: 'Molality', latex: 'm = \\frac{n}{\\text{mass of solvent in kg}}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-2', name: "Henry's Law", latex: 'p = K_H x', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-2', name: 'Elevation of Boiling Point', latex: '\\Delta T_b = K_b m', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-2', name: 'Depression in Freezing Point', latex: '\\Delta T_f = K_f m', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-2', name: "van't Hoff Factor", latex: 'i = \\frac{\\text{observed colligative property}}{\\text{calculated colligative property}}', sourceName: 'Chemistry formulas.pdf' },
  { chapterId: 'c12-chem-2', name: 'Osmotic Pressure', latex: '\\Pi = iCRT', sourceName: 'Chemistry formulas.pdf' },
  { chapterId: 'c12-chem-3', name: 'Nernst Equation', latex: 'E = E^\\circ - \\frac{0.0591}{n}\\log Q', sourceName: 'Chemistry formulas part 2.pdf' },
  { chapterId: 'c12-chem-3', name: 'Cell Potential', latex: 'E_{\\mathrm{cell}} = E^\\circ_{\\mathrm{cathode}} - E^\\circ_{\\mathrm{anode}}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-3', name: 'Gibbs Energy and EMF', latex: '\\Delta G = -nFE', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-3', name: "Faraday's First Law", latex: 'm = ZIt', sourceName: 'Chemistry formulas part 2.pdf' },
  { chapterId: 'c12-chem-3', name: 'Molar Conductivity', latex: '\\Lambda_m = \\frac{\\kappa \\times 1000}{C}', sourceName: 'Chemistry formula 3.pdf' },
  { chapterId: 'c12-chem-4', name: 'Rate Law', latex: 'r = k[A]^m[B]^n', sourceName: 'Chemistry formulas part 2.pdf' },
  { chapterId: 'c12-chem-4', name: 'Integrated First-order Rate Constant', latex: 'k = \\frac{2.303}{t}\\log\\frac{a}{a-x}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-4', name: 'First-order Half-life', latex: 't_{1/2} = \\frac{0.693}{k}', sourceName: 'Chemistry formula 3.pdf' },
  { chapterId: 'c12-chem-4', name: 'Zero-order Half-life', latex: 't_{1/2} = \\frac{[A]_0}{2k}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-4', name: 'Arrhenius Equation', latex: 'k = A e^{-E_a/(RT)}', sourceName: 'Chemistry formula 3.pdf' },
  { chapterId: 'c12-chem-5', name: 'Freundlich Adsorption Isotherm', latex: '\\frac{x}{m} = kP^{1/n}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-chem-12', name: 'Aldehyde Reduction', latex: 'RCHO + [H] \\rightarrow RCH_2OH', sourceName: 'Chemistry formulas.pdf' },
  { chapterId: 'c12-chem-12', name: 'Ketone Reduction', latex: 'R_2CO + [H] \\rightarrow R_2CHOH', sourceName: 'Chemistry formulas.pdf' },

  { chapterId: 'c12-bio-3', name: 'Population Growth (J-curve)', latex: '\\frac{dN}{dt} = rN', sourceName: 'Formula-Book_Biology-1.pdf' },
  { chapterId: 'c12-bio-3', name: 'Logistic Growth', latex: '\\frac{dN}{dt} = rN\\left(1-\\frac{N}{K}\\right)', sourceName: 'Formula-Book_Biology-1.pdf' },
  { chapterId: 'c12-bio-6', name: 'DNA Composition Rule', latex: 'A = T,\\; G = C', sourceName: 'Formula-Book_Biology-1.pdf' },
  { chapterId: 'c12-bio-13', name: 'Biomass Pyramid Trend', latex: '\\text{Producers} > \\text{Herbivores} > \\text{Carnivores}', sourceName: 'Formula-Book_Biology-1.pdf' },

  { chapterId: 'c12-math-2', name: 'Inverse Trig Identity', latex: '\\sin^{-1}x + \\cos^{-1}x = \\frac{\\pi}{2}', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-4', name: 'Inverse of Matrix', latex: 'A^{-1} = \\frac{\\operatorname{adj}(A)}{|A|}', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-4', name: 'Area using Determinants', latex: '\\Delta = \\frac{1}{2}\\left|\\begin{matrix}x_1 & y_1 & 1 \\\\ x_2 & y_2 & 1 \\\\ x_3 & y_3 & 1\\end{matrix}\\right|', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-5', name: 'Derivative Definition', latex: 'f^{\\prime}(x) = \\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-6', name: 'Tangent Equation', latex: 'y - y_1 = m(x - x_1)', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-6', name: 'Normal Equation', latex: 'y - y_1 = -\\frac{1}{m}(x - x_1)', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-7', name: 'Integration by Parts', latex: '\\int u\\,dv = uv - \\int v\\,du', sourceName: 'Maths book 3.pdf' },
  { chapterId: 'c12-math-7', name: 'Standard Integral', latex: '\\int \\frac{dx}{a^2 + x^2} = \\frac{1}{a}\\tan^{-1}\\left(\\frac{x}{a}\\right) + C', sourceName: 'documents_148581-489262829-class-12-mathematics-all-formulas.pdf' },
  { chapterId: 'c12-math-8', name: 'Area under Curve', latex: '\\text{Area} = \\int_a^b y\\,dx', sourceName: 'Maths formulas.pdf' },
  { chapterId: 'c12-math-8', name: 'Area between Two Curves', latex: '\\int_a^b [y_\\text{upper} - y_\\text{lower}]\\,dx', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-9', name: 'Variable Separable DE', latex: '\\frac{dy}{dx} = g(x)h(y) \\Rightarrow \\int \\frac{1}{h(y)}dy = \\int g(x)dx', sourceName: 'Maths book 3.pdf' },
  { chapterId: 'c12-math-9', name: 'Integrating Factor', latex: '\\text{IF} = e^{\\int P(x)\\,dx}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-10', name: 'Magnitude of Vector', latex: '|\\vec{a}| = \\sqrt{a_1^2 + a_2^2 + a_3^2}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-10', name: 'Dot Product', latex: '\\vec{a}\\cdot\\vec{b} = |\\vec{a}|\\,|\\vec{b}|\\cos\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-10', name: 'Cross Product Magnitude', latex: '|\\vec{a}\\times\\vec{b}| = |\\vec{a}|\\,|\\vec{b}|\\sin\\theta', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-11', name: 'Line in Vector Form', latex: '\\vec{r} = \\vec{a} + \\lambda\\vec{b}', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-11', name: 'Plane Equation', latex: '\\vec{r}\\cdot\\vec{n} = d', sourceName: 'NCERT formula set (curated)' },
  { chapterId: 'c12-math-13', name: "Bayes' Theorem", latex: 'P(A_i|B) = \\frac{P(A_i)P(B|A_i)}{\\sum_j P(A_j)P(B|A_j)}', sourceName: 'Maths formulas.pdf' },

  { chapterId: 'c12-acc-1', name: 'Sacrificing Ratio', latex: '\\text{Old Share} - \\text{New Share}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-acc-1', name: 'Gaining Ratio', latex: '\\text{New Share} - \\text{Old Share}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-acc-4', name: 'Current Ratio', latex: '\\frac{\\text{Current Assets}}{\\text{Current Liabilities}}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-acc-4', name: 'Quick Ratio', latex: '\\frac{\\text{Current Assets} - \\text{Inventory}}{\\text{Current Liabilities}}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-acc-4', name: 'Debt-Equity Ratio', latex: '\\frac{\\text{Total Debt}}{\\text{Shareholders Equity}}', sourceName: 'Class 12 Accountancy Ratio Chapter (reference)', sourceUrl: 'https://www.vedantu.com/content-files-downloadable/ncert-solutions/ncert-solutions-class-12-accountancy-company-accounts-and-analysis-of-financial-statements-chapter-5.pdf' },
  { chapterId: 'c12-acc-4', name: 'Return on Capital Employed', latex: '\\frac{\\text{EBIT}}{\\text{Capital Employed}} \\times 100', sourceName: 'Class 12 Accountancy Ratio Chapter (reference)', sourceUrl: 'https://www.vedantu.com/content-files-downloadable/ncert-solutions/ncert-solutions-class-12-accountancy-company-accounts-and-analysis-of-financial-statements-chapter-5.pdf' },
  { chapterId: 'c12-acc-5', name: 'Net Cash Flow', latex: '\\text{CFO} + \\text{CFI} + \\text{CFF}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-acc-5', name: 'Cash From Operating Activities (Indirect)', latex: '\\text{Net Profit Before Tax} + \\text{Non-cash items} - \\text{Non-operating incomes} \\pm \\Delta\\text{Working Capital}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-bst-2', name: 'Contribution per Unit', latex: '\\text{Selling Price per Unit} - \\text{Variable Cost per Unit}', sourceName: 'Break-even formula reference', sourceUrl: 'https://www.investopedia.com/ask/answers/032715/how-can-i-calculate-breakeven-analysis-excel.asp' },
  { chapterId: 'c12-bst-2', name: 'Break-even Point (Units)', latex: '\\frac{\\text{Fixed Cost}}{\\text{Contribution per Unit}}', sourceName: 'Break-even formula reference', sourceUrl: 'https://www.investopedia.com/ask/answers/032715/how-can-i-calculate-breakeven-analysis-excel.asp' },
  { chapterId: 'c12-bst-3', name: 'Break-even Sales Value', latex: '\\frac{\\text{Fixed Cost}}{\\text{P/V Ratio}}', sourceName: 'Break-even formula reference', sourceUrl: 'https://www.investopedia.com/ask/answers/032715/how-can-i-calculate-breakeven-analysis-excel.asp' },
  { chapterId: 'c12-eco-1', name: 'Real GDP', latex: '\\frac{\\text{Nominal GDP}}{\\text{GDP Deflator}} \\times 100', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-1', name: 'GDP at Market Price', latex: '\\text{GDP}_{FC} + \\text{Net Indirect Taxes}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-2', name: 'Average Propensity to Consume', latex: '\\text{APC} = \\frac{C}{Y}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-2', name: 'Marginal Propensity to Consume', latex: '\\text{MPC} = \\frac{\\Delta C}{\\Delta Y}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-2', name: 'Marginal Propensity to Save', latex: '\\text{MPS} = \\frac{\\Delta S}{\\Delta Y}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-3', name: 'Multiplier', latex: 'k = \\frac{1}{1-\\text{MPC}}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-3', name: 'Multiplier (Savings form)', latex: 'k = \\frac{1}{\\text{MPS}}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-3', name: 'Money Multiplier', latex: '\\frac{1}{\\text{Reserve Ratio}}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-4', name: 'Fiscal Deficit', latex: '\\text{Total Expenditure} - \\text{Total Receipts (excluding borrowings)}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-4', name: 'Revenue Deficit', latex: '\\text{Revenue Expenditure} - \\text{Revenue Receipts}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-4', name: 'Primary Deficit', latex: '\\text{Fiscal Deficit} - \\text{Interest Payments}', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-5', name: 'Terms of Trade', latex: '\\frac{\\text{Export Price Index}}{\\text{Import Price Index}}\\times100', sourceName: 'Commerce formula set (curated)' },
  { chapterId: 'c12-eco-5', name: 'Balance of Trade', latex: '\\text{Exports} - \\text{Imports}', sourceName: 'Commerce formula set (curated)' },
];
