#!/usr/bin/env node
/**
 * Post-build context chunk sanitizer.
 *
 * Cleans and compacts chunk artifacts generated by:
 *   - scripts/build_context_index.py
 *   - scripts/build_textbook_index.py
 *
 * Why:
 *   - Strip instruction boilerplate that can still leak through.
 *   - Remove control / ambiguous unicode noise.
 *   - Drop ultra-short / low-signal chunks.
 *   - De-duplicate near-identical chunks.
 *
 * Usage:
 *   node scripts/clean_context_chunks.mjs
 *   node scripts/clean_context_chunks.mjs --min-words 55
 *   node scripts/clean_context_chunks.mjs --dry-run
 */

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const contextDir = path.join(root, "lib", "context");

const DEFAULT_MIN_WORDS = 55;
const DEFAULT_MIN_ALPHA_RATIO = 0.42;
const DEFAULT_MIN_UNIQUE_RATIO = 0.28;

function parseArgs(argv) {
  const args = {
    minWords: DEFAULT_MIN_WORDS,
    minAlphaRatio: DEFAULT_MIN_ALPHA_RATIO,
    minUniqueRatio: DEFAULT_MIN_UNIQUE_RATIO,
    dryRun: false,
    files: [],
  };

  for (let i = 2; i < argv.length; i++) {
    const token = argv[i];
    if (token === "--dry-run") {
      args.dryRun = true;
      continue;
    }
    if (token === "--min-words") {
      args.minWords = Number(argv[++i] ?? DEFAULT_MIN_WORDS);
      continue;
    }
    if (token === "--min-alpha-ratio") {
      args.minAlphaRatio = Number(argv[++i] ?? DEFAULT_MIN_ALPHA_RATIO);
      continue;
    }
    if (token === "--min-unique-ratio") {
      args.minUniqueRatio = Number(argv[++i] ?? DEFAULT_MIN_UNIQUE_RATIO);
      continue;
    }
    if (token === "--file") {
      const rel = argv[++i];
      if (rel) args.files.push(path.resolve(root, rel));
      continue;
    }
    if (token === "--help" || token === "-h") {
      printHelpAndExit(0);
    }
    console.error(`[clean-chunks] Unknown arg: ${token}`);
    printHelpAndExit(1);
  }

  if (!Number.isFinite(args.minWords) || args.minWords < 1) {
    throw new Error("--min-words must be >= 1");
  }
  if (!Number.isFinite(args.minAlphaRatio) || args.minAlphaRatio <= 0 || args.minAlphaRatio > 1) {
    throw new Error("--min-alpha-ratio must be in (0, 1]");
  }
  if (!Number.isFinite(args.minUniqueRatio) || args.minUniqueRatio <= 0 || args.minUniqueRatio > 1) {
    throw new Error("--min-unique-ratio must be in (0, 1]");
  }
  if (args.files.length === 0) {
    args.files = [
      path.join(contextDir, "chunks.jsonl"),
      path.join(contextDir, "textbook_chunks.jsonl"),
    ];
  }

  return args;
}

function printHelpAndExit(code) {
  console.log(
    [
      "Usage: node scripts/clean_context_chunks.mjs [options]",
      "",
      "Options:",
      "  --min-words <n>          Drop chunks below n words (default: 55)",
      "  --min-alpha-ratio <r>    Minimum letter/printable ratio (default: 0.42)",
      "  --min-unique-ratio <r>   Minimum unique token ratio (default: 0.28)",
      "  --file <path>            Process only this JSONL file (repeatable)",
      "  --dry-run                Report only; do not rewrite files",
      "  -h, --help               Show this help",
    ].join("\n")
  );
  process.exit(code);
}

const CONTROL_RE = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/g;
const ZERO_WIDTH_RE = /[\u200B-\u200F\u202A-\u202E\u2060\uFEFF]/g;
const PRIVATE_USE_RE = /[\uE000-\uF8FF]/g;
const REPLACEMENT_RE = /\uFFFD/g;
const MULTI_SPACE_RE = /[ \t]+/g;
const MULTI_NL_RE = /\n{3,}/g;

const EXAM_BLOCK_PATTERNS = [
  /\b(?:General Instructions|Read the following instructions carefully)\b[\s\S]{0,1800}?(?=(?:\bSection\s+[A-F]\b|\bQ\.?\s*1\b|\bQuestion\s*1\b|$))/gi,
  /\bCandidates must write the Q\.?P\.?\s*Code[\s\S]{0,900}?(?=(?:\bSection\s+[A-F]\b|\bQ\.?\s*1\b|\bQuestion\s*1\b|$))/gi,
];

const EXAM_LINE_PATTERNS = [
  /\bTime allowed\s*[:\-]?\s*[^.]{0,140}\.?/gi,
  /\bMaximum Marks?\s*[:\-]?\s*[^.]{0,140}\.?/gi,
  /\bQ\.?P\.?\s*Code\s*[:\-]?\s*[^.]{0,80}\.?/gi,
  /\bRoll No\.?\s*[:\-]?\s*[^.]{0,80}\.?/gi,
  /\bPlease check that this question paper[^.]{0,220}\.?/gi,
  /\bThis question paper contains[^.]{0,220}\.?/gi,
  /\bDo not write anything on the question paper[^.]{0,220}\.?/gi,
];

const PAGE_NOISE_PATTERNS = [
  /\bPage\s+\d+\s+of\s+\d+\b/gi,
  /\b(?:www\.)?ncert\.nic\.in\b/gi,
  /\b(?:CBSE|NCERT)\b\s*(?:\d{4}(?:-\d{2})?)?/gi,
];

const INSTRUCTION_MARKERS = [
  "general instructions",
  "time allowed",
  "maximum marks",
  "q.p. code",
  "roll no",
  "please check that this question paper",
  "this question paper contains",
  "read the following instructions carefully",
];

function cleanText(text) {
  let out = String(text ?? "");
  out = out.normalize("NFKC");
  out = out.replace(REPLACEMENT_RE, " ");
  out = out.replace(CONTROL_RE, " ");
  out = out.replace(ZERO_WIDTH_RE, "");
  out = out.replace(PRIVATE_USE_RE, " ");
  out = out.replace(/\r\n?/g, "\n");

  for (const pattern of EXAM_BLOCK_PATTERNS) out = out.replace(pattern, " ");
  for (const pattern of EXAM_LINE_PATTERNS) out = out.replace(pattern, " ");
  for (const pattern of PAGE_NOISE_PATTERNS) out = out.replace(pattern, " ");

  out = out.replace(MULTI_SPACE_RE, " ");
  out = out.replace(MULTI_NL_RE, "\n\n");
  out = out.replace(/\s+/g, " ").trim();
  return out;
}

function wordTokens(text) {
  return text.match(/[\p{L}\p{N}]+/gu) ?? [];
}

function alphaAndPrintableRatio(text) {
  const printableChars = Array.from(text.replace(/\s+/g, ""));
  if (printableChars.length === 0) return 0;
  const alphaCount = (text.match(/[\p{L}]/gu) ?? []).length;
  return alphaCount / printableChars.length;
}

function uniqueRatio(tokens) {
  if (tokens.length === 0) return 0;
  return new Set(tokens.map((t) => t.toLowerCase())).size / tokens.length;
}

function looksLikeInstructionChunk(text) {
  const lower = text.toLowerCase();
  let hits = 0;
  for (const marker of INSTRUCTION_MARKERS) {
    if (lower.includes(marker)) hits += 1;
  }
  const questionHits = (lower.match(/\b(question|q\.?\s*\d+|solve|calculate|evaluate|prove|show that)\b/g) ?? []).length;
  return hits >= 2 && questionHits < 3;
}

function dedupeKey(text) {
  const canonical = text
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
  return crypto.createHash("sha1").update(canonical).digest("hex");
}

function processFile(filePath, config) {
  if (!fs.existsSync(filePath)) {
    return {
      filePath,
      skipped: true,
      reason: "not_found",
    };
  }

  const rawLines = fs
    .readFileSync(filePath, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const seen = new Set();
  const outLines = [];

  const stats = {
    total: 0,
    kept: 0,
    dropped_json_parse: 0,
    dropped_missing_text: 0,
    dropped_short: 0,
    dropped_low_alpha: 0,
    dropped_low_unique: 0,
    dropped_instruction: 0,
    dropped_duplicate: 0,
    cleaned_text_changed: 0,
  };

  for (const line of rawLines) {
    stats.total += 1;
    let obj;
    try {
      obj = JSON.parse(line);
    } catch {
      stats.dropped_json_parse += 1;
      continue;
    }
    if (!obj || typeof obj !== "object" || typeof obj.text !== "string") {
      stats.dropped_missing_text += 1;
      continue;
    }

    const cleaned = cleanText(obj.text);
    if (cleaned !== obj.text) stats.cleaned_text_changed += 1;
    if (!cleaned) {
      stats.dropped_short += 1;
      continue;
    }
    if (looksLikeInstructionChunk(cleaned)) {
      stats.dropped_instruction += 1;
      continue;
    }

    const tokens = wordTokens(cleaned);
    if (tokens.length < config.minWords) {
      stats.dropped_short += 1;
      continue;
    }
    if (alphaAndPrintableRatio(cleaned) < config.minAlphaRatio) {
      stats.dropped_low_alpha += 1;
      continue;
    }
    if (uniqueRatio(tokens) < config.minUniqueRatio) {
      stats.dropped_low_unique += 1;
      continue;
    }

    const key = dedupeKey(cleaned);
    if (seen.has(key)) {
      stats.dropped_duplicate += 1;
      continue;
    }
    seen.add(key);

    obj.text = cleaned;
    if (typeof obj.wordCount === "number") {
      obj.wordCount = tokens.length;
    }

    outLines.push(JSON.stringify(obj, null, 0));
    stats.kept += 1;
  }

  if (!config.dryRun) {
    const tmpPath = `${filePath}.tmp`;
    fs.writeFileSync(tmpPath, outLines.join("\n") + (outLines.length ? "\n" : ""), "utf8");
    fs.renameSync(tmpPath, filePath);
  }

  return {
    filePath,
    skipped: false,
    stats,
  };
}

function summarize(result) {
  if (result.skipped) {
    console.log(`[clean-chunks] Skip ${path.relative(root, result.filePath)} (${result.reason})`);
    return;
  }
  const s = result.stats;
  console.log(
    [
      `[clean-chunks] ${path.relative(root, result.filePath)}`,
      `  total=${s.total} kept=${s.kept} dropped=${s.total - s.kept}`,
      `  dropped_short=${s.dropped_short} dropped_instruction=${s.dropped_instruction} dropped_duplicate=${s.dropped_duplicate}`,
      `  dropped_low_alpha=${s.dropped_low_alpha} dropped_low_unique=${s.dropped_low_unique}`,
      `  cleaned_text_changed=${s.cleaned_text_changed}`,
    ].join("\n")
  );
}

function main() {
  const args = parseArgs(process.argv);
  let keptTotal = 0;
  let inputTotal = 0;

  for (const filePath of args.files) {
    const result = processFile(filePath, args);
    summarize(result);
    if (!result.skipped) {
      keptTotal += result.stats.kept;
      inputTotal += result.stats.total;
    }
  }

  console.log(
    `[clean-chunks] Done. dryRun=${args.dryRun ? "yes" : "no"} kept=${keptTotal} input=${inputTotal} removed=${Math.max(
      0,
      inputTotal - keptTotal
    )}`
  );
}

main();
