"""
VidyaPath — HF URL Generator
==============================
After uploading the dataset to Hugging Face, run this script to
generate a mapping of every PDF file to its HF URL.

This outputs a TypeScript snippet you can paste into lib/papers.ts
to replace the CBSE fallback URLs with real direct-download links.

Usage:
    pip install huggingface_hub
    python scripts/generate_hf_urls.py > hf_url_map.ts

    # Or filter to just the subjects we care about:
    python scripts/generate_hf_urls.py --filter "Physics,Chemistry,Biology,Math,Science,Mathematics"
"""

import argparse
import json
import urllib.parse
from pathlib import Path

HF_REPO_ID = "adithya-s-nair/cbse-papers-2009-2025"
HF_BASE    = f"https://huggingface.co/datasets/{HF_REPO_ID}/resolve/main"

# Map folder names → our subject keys
SUBJECT_MAP = {
    "Physics":     "Physics",
    "Chemistry":   "Chemistry",
    "Biology":     "Biology",
    "Mathematics": "Math",
    "Math":        "Math",
    "Science":     "Science",
}

def hf_url(path: str) -> str:
    encoded = "/".join(urllib.parse.quote(seg) for seg in path.split("/"))
    return f"{HF_BASE}/{encoded}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--filter", default="", help="Comma-separated subject folder names to include")
    parser.add_argument("--local-dir", default="dataset/cbse_papers", help="Local dataset path")
    args = parser.parse_args()

    allowed = {s.strip() for s in args.filter.split(",")} if args.filter else None
    local_root = Path(args.local_dir)

    if not local_root.exists():
        # Fall back to listing from HF API
        try:
            from huggingface_hub import list_repo_tree
        except ImportError:
            print("// ERROR: Run `pip install huggingface_hub` or make sure dataset/ exists locally")
            return

        print("// Fetching file list from Hugging Face API...")
        files = [
            item.path for item in list_repo_tree(HF_REPO_ID, repo_type="dataset", recursive=True)
            if item.path.endswith(".pdf")
        ]
    else:
        files = [
            str(p.relative_to(local_root)).replace("\\", "/")
            for p in local_root.rglob("*.pdf")
        ]

    # Group by year/class/subject
    mapping: dict[str, list[dict]] = {}

    for filepath in sorted(files):
        parts = filepath.split("/")
        if len(parts) < 3:
            continue

        year    = parts[0]   # e.g. "2025" or "2024-COMPTT"
        cls     = parts[1]   # e.g. "Class_10"
        subj_dir = parts[2]  # e.g. "Physics"

        if allowed and subj_dir not in allowed:
            continue

        subject = SUBJECT_MAP.get(subj_dir, subj_dir)
        key     = f"{year}/{cls}/{subject}"

        if key not in mapping:
            mapping[key] = []

        filename = parts[-1]
        mapping[key].append({
            "file": filename,
            "url": hf_url(filepath),
        })

    # Output as a TypeScript const
    print("// Auto-generated by scripts/generate_hf_urls.py")
    print("// Paste the relevant entries into lib/papers.ts\n")
    print("export const HF_PAPER_URLS = {")
    for key, entries in sorted(mapping.items()):
        print(f"  // {key}")
        for entry in entries:
            safe_name = entry["file"].replace('"', '\\"')
            print(f'  "{safe_name}": "{entry["url"]}",')
        print()
    print("} as const;")
    print(f"\n// Total: {sum(len(v) for v in mapping.values())} files")


if __name__ == "__main__":
    main()
